<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Exam Rooms</name>
   <tag></tag>
   <elementGuidId>b2c1eb0e-f016-4ab3-87fe-315f21b93576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.zchip[data-zone=&quot;exam&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'exam')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Exam Rooms&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07d49ee2-ee69-450f-90ee-95ffb450500d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zchip</value>
      <webElementGuid>55fd8fad-5303-4014-8d5e-c99965275787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6401ff2a-d6a3-47eb-ba0c-7e8a643eed7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zone</name>
      <type>Main</type>
      <value>exam</value>
      <webElementGuid>d1cdddb8-7c54-4208-af34-792acf7c0033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exam Rooms</value>
      <webElementGuid>e8d42fc6-3974-4083-b5b6-e5714e86ad85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd1f7a43294abf5d5a5421e640c4c18c</value>
      <webElementGuid>434f7d11-f095-43b6-aad5-760f33a97a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'exam')]</value>
      <webElementGuid>4e190cfc-fe71-48ac-964f-3345e315fedb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'exam')]</value>
      <webElementGuid>44a260be-df64-47a3-849c-1a1cc6ec83d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Exam Rooms' or . = 'Exam Rooms')]</value>
      <webElementGuid>7d00925b-37af-45b1-a0b3-d6b59d4e4ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
