<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Patient Comms</name>
   <tag></tag>
   <elementGuidId>5002fad4-baa7-498f-83a6-8bd2f74d5dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.zchip[data-zone=&quot;patient&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'patient')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Patient Comms&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a87b58f-1386-4c45-b7a3-1dce729ee245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zchip</value>
      <webElementGuid>f5770b33-8dd6-4288-9304-0fd5846a93e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d035013-8801-433f-8178-ff52b14c3f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zone</name>
      <type>Main</type>
      <value>patient</value>
      <webElementGuid>0db64f51-008b-48e5-b79b-a6773215070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient Comms</value>
      <webElementGuid>ad7458f4-638b-4fe1-9f82-6b7e348d9d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2c0ab5d0d10a6ebb5eeedc93c171732a</value>
      <webElementGuid>7ec8121b-944f-424c-89a9-aa110a751a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'patient')]</value>
      <webElementGuid>826b4a1a-ec4b-4ee0-a057-6e112b086246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'patient')]</value>
      <webElementGuid>3f71977c-e4aa-4d4b-87bf-5a7b566f9c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Patient Comms' or . = 'Patient Comms')]</value>
      <webElementGuid>929aea7d-2c61-40bf-92d4-400448cee73e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
