<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Optical  meet EVAA Assistant</name>
   <tag></tag>
   <elementGuidId>32d97065-0933-44a9-a3e1-4b6333be7e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Optical\ —\ meet\ EVAA\ Assistant&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Optical — meet EVAA Assistant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Optical — meet EVAA Assistant&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>190bc78f-4a06-421a-8867-496c69d6f025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs</value>
      <webElementGuid>c729c0fb-e4ee-4153-a141-875028360672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a799423-cfa6-4c35-a410-444bde7ed8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zone</name>
      <type>Main</type>
      <value>optical</value>
      <webElementGuid>f6084327-f2f1-40a3-b94c-e580f284c86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Optical — meet EVAA Assistant</value>
      <webElementGuid>d8dd1f79-33a4-4dd2-9488-b5617846530d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AOptical</value>
      <webElementGuid>04960214-1aee-4424-9c53-c8403210df02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4d4a955896f585c68df1513fe5bf1bde</value>
      <webElementGuid>eda84fc0-e62d-44c6-9337-475a1d96b381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Optical — meet EVAA Assistant']</value>
      <webElementGuid>8f9a33ca-1041-4bf8-9fa6-901130d17d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Optical — meet EVAA Assistant']</value>
      <webElementGuid>d224db49-db97-465f-85f2-9c49347b2cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'AOptical' or . = 'AOptical')]</value>
      <webElementGuid>b644d93f-0cdb-4710-9757-26b6d888f76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
