<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reception</name>
   <tag></tag>
   <elementGuidId>e30dbe30-b35a-42e3-84c9-0857f3c30704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.zchip[data-zone=&quot;reception&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'reception')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Reception&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7874fe6d-3080-4835-96ba-e89f89ec6593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zchip</value>
      <webElementGuid>4392692d-6030-449f-8e18-76058e407803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2564fca-fa9a-456f-91c6-0e36fe824abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zone</name>
      <type>Main</type>
      <value>reception</value>
      <webElementGuid>04d334d6-1889-4bb0-9f67-6cdd445aa112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reception</value>
      <webElementGuid>e94a85d2-db21-440a-a3fd-2b0da89b1af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-25bef13e76d188fa2a6573a9332b3159</value>
      <webElementGuid>523c26c3-b6eb-4c84-a7c8-9b1ef463d865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'reception')]</value>
      <webElementGuid>c3d8c10a-8921-40bd-b894-e40241352547</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' zchip ') and (@data-zone = 'reception')]</value>
      <webElementGuid>c8c40b5b-d3b3-4697-bff6-8535c54b604e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Reception' or . = 'Reception')]</value>
      <webElementGuid>d182da24-e211-451d-b353-19edc683343a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
