<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hs_form_target_widget_1756331635880-6-error</name>
   <tag></tag>
   <elementGuidId>fbc9fa7b-f2b2-4d20-b19d-de7a5aff771a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hsfc-ErrorAlert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Error: Please complete this required field.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81fc02eb-33c7-44a1-9ab6-6439421d43a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>ErrorAlert</value>
      <webElementGuid>c361e526-2565-43f4-abf4-9597d6294056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-6-error</value>
      <webElementGuid>a4e9f28d-4c9c-4b73-b79f-d2757c58d091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>1cd11227-806e-42c9-8e16-702fca9b0562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>33c9242a-f001-4650-a0f7-d511525f733d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-ErrorAlert</value>
      <webElementGuid>97ad7151-172e-4d3d-8755-9766137d6dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error:  Please complete this required field.</value>
      <webElementGuid>f40b97ba-c40e-4894-b817-93fa2bc5c841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-373cf75a5b6d27cce0745fa9f35a375b</value>
      <webElementGuid>cbe982a2-9e21-46f3-b97f-9e102c2ddc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>65a0dd69-3b13-43a2-91a2-e13a218c91b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>99895865-9094-4d74-a037-7b917a66eff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hs_form_target_widget_1756331635880-6-error' and (text() = 'Error:  Please complete this required field.' or . = 'Error:  Please complete this required field.')]</value>
      <webElementGuid>483bf3e5-806d-483e-80e4-311dd07fa07d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
