<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hs_form_target_widget_1756331635880-6-error_1</name>
   <tag></tag>
   <elementGuidId>16e2d50d-64a7-4869-9153-64f699c0b392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hsfc-TextField:nth-child(1) .hsfc-ErrorAlert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-TextField ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hs_form_target_widget_1756331635880-6-error</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cda165a9-4437-432c-95ac-dd6ab571109f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>ErrorAlert</value>
      <webElementGuid>12812686-a0ae-4453-9a54-06d8c0d76d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-6-error</value>
      <webElementGuid>200b5d47-47a2-4261-baec-befcb52532c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>8a37ea8e-770d-4c9b-bd4c-d826793efb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>956dd206-74f7-47bf-95f0-bde24be245f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-ErrorAlert</value>
      <webElementGuid>eb9bcc0f-8ec5-4a69-8004-1f37d70ce3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error:  Please complete this required field.</value>
      <webElementGuid>362a9ce0-22a9-4676-9f86-5e2952398744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-43a01ee0087f192ba3ffbe4ee35bd783</value>
      <webElementGuid>7a15c45a-9917-4018-868f-3b9450dddf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-TextField ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>541462e2-a7fa-4046-a6bf-ea75eb693d15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-TextField ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>bc391d8f-5503-4d23-b1d0-5864aaba7d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hs_form_target_widget_1756331635880-6-error' and (text() = 'Error:  Please complete this required field.' or . = 'Error:  Please complete this required field.')]</value>
      <webElementGuid>a649b65f-02cc-4d24-b441-ece0895b3c0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
