<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hs_form_target_widget_1756331635880-4-error</name>
   <tag></tag>
   <elementGuidId>cf8d5311-6956-4027-a743-c7dff7e7cc84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hsfc-PhoneField .hsfc-ErrorAlert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-PhoneField ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hs_form_target_widget_1756331635880-4-error</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa2863e1-f821-4b27-8b16-1b49b638462a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>ErrorAlert</value>
      <webElementGuid>17cd27d1-63a8-4e2f-af4f-f21d4daddb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-4-error</value>
      <webElementGuid>540491d0-3348-4ce4-9f65-70988a436910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>73b337dc-1cb3-4256-8bf8-91ad061264cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>fdbae0e9-c5d3-4f16-b226-0b928c4e161a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-ErrorAlert</value>
      <webElementGuid>efefc4bb-bf41-4a7f-9138-feb234975d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error:  Please complete this required field.</value>
      <webElementGuid>efef3610-bdca-4b64-92da-2647464a50cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-eca87ae03fa925e16e51a89f8ed38a96</value>
      <webElementGuid>b530a09e-0b7c-4dfe-aab3-fb1508c27a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-PhoneField ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>2d0f86f0-29be-43ee-929d-1968f00f6232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-PhoneField ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>c4f8b951-2186-41f2-9780-3535687133cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hs_form_target_widget_1756331635880-4-error' and (text() = 'Error:  Please complete this required field.' or . = 'Error:  Please complete this required field.')]</value>
      <webElementGuid>9bd66e68-fbc4-4c91-83c1-d5291003e6c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
