<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hs_form_target_widget_1756331635880-3-error</name>
   <tag></tag>
   <elementGuidId>66b38264-8fc6-41a6-884a-8835e69a53b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hsfc-EmailField .hsfc-ErrorAlert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-EmailField ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hs_form_target_widget_1756331635880-3-error</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5729a653-5a97-47ae-92b0-4e97ebac010c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>ErrorAlert</value>
      <webElementGuid>a8cea03c-0517-4964-8573-4d0104d0d4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-3-error</value>
      <webElementGuid>92ad0573-bbda-4ac5-8244-202fd18606cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>dc4802a6-8fd3-4c88-9f21-0f3e6176f7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>63912a8d-5745-4ed4-898a-34c31a0661be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-ErrorAlert</value>
      <webElementGuid>52db0c4f-bc20-4d0b-97ae-688edec9ac72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error:  Please complete this required field.</value>
      <webElementGuid>b45da9fb-5b5d-4ad6-b153-f812cecc7093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-19122d702d454b6366f0f6905743ffd9</value>
      <webElementGuid>a66d5e15-f341-43a7-828b-ad347366e970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-EmailField ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>47e6a80c-e917-4dd1-a5e5-eb994eb04d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-EmailField ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>b395ecc3-c416-46f8-aba9-1b4cbaceaca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hs_form_target_widget_1756331635880-3-error' and (text() = 'Error:  Please complete this required field.' or . = 'Error:  Please complete this required field.')]</value>
      <webElementGuid>50fa2e35-deda-4762-8651-eb7c80640587</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
