<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hs_form_target_widget_1756331635880-5-error</name>
   <tag></tag>
   <elementGuidId>a2bcf7d9-eac5-45d8-9237-4f2ab02736f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hsfc-TextField:nth-child(2) .hsfc-ErrorAlert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-TextField ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hs_form_target_widget_1756331635880-5-error</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c40aa989-3718-46d3-a6d3-1e2162ae822e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>ErrorAlert</value>
      <webElementGuid>899b456b-786a-47d6-9aa8-c041d6648bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-5-error</value>
      <webElementGuid>77a82816-f63d-44e9-9b2c-0e56caa59fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>d0ec2ca3-f4c0-4bb4-b2f3-4b16b07bf634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>cbd79eb1-5a63-44fb-b696-31c23b53d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-ErrorAlert</value>
      <webElementGuid>1181206f-0f77-46d7-aa9c-1ac3c571afba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error:  Please complete this required field.</value>
      <webElementGuid>2fb62e6b-7855-4f76-94c0-09394436d357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-16fd322bb69820867497f7e384d42b55</value>
      <webElementGuid>f9c1021a-477a-472f-9110-8498a7e6ab62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-TextField ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>337ab6ae-8a0b-4806-8f9f-726a53f18a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-TextField ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-ErrorAlert ')]</value>
      <webElementGuid>05812672-1eb0-4e93-974a-56898bdeaa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hs_form_target_widget_1756331635880-5-error' and (text() = 'Error:  Please complete this required field.' or . = 'Error:  Please complete this required field.')]</value>
      <webElementGuid>03e1fb56-6df9-4d95-a957-641fa761cbb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
