<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rc-anchor-normal-footer</name>
   <tag></tag>
   <elementGuidId>9769953b-e6ca-4b85-a171-ba1237a83d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rc-anchor-normal-footer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rc-anchor-normal-footer ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-anchor-normal-footer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ef53c47-160a-421d-b19f-1fa03d87b965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-anchor-normal-footer</value>
      <webElementGuid>af7c4985-2093-42b3-9b0b-84f0070adeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6a00c4ccca265e4f792c73ba5376aa16</value>
      <webElementGuid>0391b6ff-e7f8-4875-9aac-064134d76250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rc-anchor-normal-footer ')]</value>
      <webElementGuid>11fabb4f-b497-4d1c-8023-adb6dfc6c2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVVA/Demo Request/iframe_a-ab95e0orn0xp</value>
      <webElementGuid>c086665d-20fc-4206-a7dd-7bd5c3825382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rc-anchor-normal-footer ')]</value>
      <webElementGuid>ad74b866-ca6b-469d-b117-0fad54c7225a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
