<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-ab95e0orn0xp</name>
   <tag></tag>
   <elementGuidId>813cf5d8-bbbf-4116-8d58-ecfa7904c446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;a-ab95e0orn0xp&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'a-ab95e0orn0xp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-ab95e0orn0xp&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7949afd1-6e04-4dec-8811-7076e153df1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>ca0c9d09-7a79-4564-906b-7ed10f82ebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>29fb2022-2c23-4e16-82de-fa8b9ba23a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>fea1514e-0949-44f0-8261-18d840656434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e5ef0518-1244-48a3-b418-764e6e4b8c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-ab95e0orn0xp</value>
      <webElementGuid>695d1c04-335c-4dcc-a8c7-7abb03404afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>302cef70-e3fe-452f-ba6e-32ffadf25a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d41e98b9-f016-4b3c-82f3-e0f6c11a6afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>3ee7c95d-4ca1-4383-af36-0cc48df56657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://google.com/recaptcha/enterprise/anchor?ar=1&amp;k=6LdGZJsoAAAAAIwMJHRwqiAHA6A_6ZP6bTYpbgSX&amp;co=aHR0cHM6Ly9nby5tYXhpbWV5ZXMuY29tOjQ0Mw..&amp;hl=en&amp;v=8x-4t2pegToiW8KmThtO4AQt&amp;size=invisible&amp;badge=inline&amp;anchor-ms=20000&amp;execute-ms=30000&amp;cb=dvub4hk904xx</value>
      <webElementGuid>f541e899-ee91-41c4-9245-df5b5062407f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-29b37e8fc6248b39a248be91eaa7e4ce</value>
      <webElementGuid>10c05878-baec-468d-9e5f-c09f96010ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'a-ab95e0orn0xp']</value>
      <webElementGuid>01d37bba-4d04-48cd-877f-3acdd7c42b31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'a-ab95e0orn0xp']</value>
      <webElementGuid>8dd77aca-83ba-4d22-8eaf-3072c613d18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-ab95e0orn0xp' and @src = 'https://google.com/recaptcha/enterprise/anchor?ar=1&amp;k=6LdGZJsoAAAAAIwMJHRwqiAHA6A_6ZP6bTYpbgSX&amp;co=aHR0cHM6Ly9nby5tYXhpbWV5ZXMuY29tOjQ0Mw..&amp;hl=en&amp;v=8x-4t2pegToiW8KmThtO4AQt&amp;size=invisible&amp;badge=inline&amp;anchor-ms=20000&amp;execute-ms=30000&amp;cb=dvub4hk904xx']</value>
      <webElementGuid>1c4ea6ef-9881-4e03-a435-9d34421d4768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
