<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MaximEyesLogo_FullLight_RGB</name>
   <tag></tag>
   <elementGuidId>8d49d784-e6e1-46f5-8f8b-7aaac9018a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;MaximEyesLogo_FullLight_RGB&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = 'MaximEyesLogo_FullLight_RGB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;MaximEyesLogo_FullLight_RGB&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9614ef6c-08f3-4f87-8aff-5a614af3dd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=200&amp;height=48&amp;name=MaximEyesLogo_FullLight_RGB.png</value>
      <webElementGuid>6972cfd6-30e0-4490-930a-381fabafaa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-image-widget </value>
      <webElementGuid>a6d6497b-6125-408a-945f-dab9eaa565f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>b4d5bff8-f3e4-40e6-966a-9ed21b3e9ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>fdfcc7c7-ced4-4cfc-b60c-4b4891fa90ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MaximEyesLogo_FullLight_RGB</value>
      <webElementGuid>ff870813-eabf-433f-a038-2e9118bf39d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MaximEyesLogo_FullLight_RGB</value>
      <webElementGuid>66d40a01-c181-4583-94b4-da57268673c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>50d4a90a-0d34-4ca8-8e47-b4ce73750006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=100&amp;height=24&amp;name=MaximEyesLogo_FullLight_RGB.png 100w, https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=200&amp;height=48&amp;name=MaximEyesLogo_FullLight_RGB.png 200w, https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=300&amp;height=72&amp;name=MaximEyesLogo_FullLight_RGB.png 300w, https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=400&amp;height=96&amp;name=MaximEyesLogo_FullLight_RGB.png 400w, https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=500&amp;height=120&amp;name=MaximEyesLogo_FullLight_RGB.png 500w, https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=600&amp;height=144&amp;name=MaximEyesLogo_FullLight_RGB.png 600w</value>
      <webElementGuid>50aec828-ec11-4414-939b-8f57c1d25739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 200px) 100vw, 200px</value>
      <webElementGuid>e30b7bc1-e2ab-4edc-9642-33a43152b71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-11e8ae33f37eb5e9127ca6da3fe2a1cf</value>
      <webElementGuid>0080884f-0b72-4830-ae31-12daf8e63f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = 'MaximEyesLogo_FullLight_RGB']</value>
      <webElementGuid>91bb9f85-e10b-4e7a-a6a1-1bb01eeb6586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = 'MaximEyesLogo_FullLight_RGB']</value>
      <webElementGuid>52b83301-7143-478e-8c76-e1d4b2e2fc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://go.maximeyes.com/hs-fs/hubfs/MaximEyesLogo_FullLight_RGB.png?width=200&amp;height=48&amp;name=MaximEyesLogo_FullLight_RGB.png' and @alt = 'MaximEyesLogo_FullLight_RGB' and @title = 'MaximEyesLogo_FullLight_RGB']</value>
      <webElementGuid>59a028b0-4289-4e6f-8d04-0a00faeb0db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
