<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State_Region</name>
   <tag></tag>
   <elementGuidId>431fd145-20fb-479d-a2a8-584d1603a8f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\30 -1\/state&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = '0-1/state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;State/Region*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b22b4db-4dce-4a20-84bf-52f642dd35ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>TextInput</value>
      <webElementGuid>8ba78a70-102c-4653-8be0-76c6786d097b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e2b2f8c-7e39-43cf-bb80-5eba38ebdd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-2246389950098-input</value>
      <webElementGuid>f1c9a81d-0ae3-41c0-8427-539380e75dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0-1/state</value>
      <webElementGuid>0a4d27c1-69c9-45a9-8d96-a827c8be9308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e12cff1b-6acc-4ef6-ad3b-85e0ac4443fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>379cc2ba-fa41-4eb5-a5f1-64a43468674d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-2246389950098-label</value>
      <webElementGuid>a149053b-7dbd-4a9e-b85e-ef59a7cea007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level1</value>
      <webElementGuid>5bd3853b-49be-4c48-98e8-acee3f0f6ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-TextInput</value>
      <webElementGuid>bb0ca0c4-f076-4338-b530-a3a5db8c5d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6b8d06df486e724c26ede9e336e168f3</value>
      <webElementGuid>9f886173-7166-49ba-bbb4-a286e8c5bdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '0-1/state']</value>
      <webElementGuid>59f9ff5b-b7eb-42f4-aa31-fc999a64331f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '0-1/state']</value>
      <webElementGuid>da92b7de-3f88-485c-bfda-eee181756d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hs_form_target_widget_1756331635880-2246389950098-input' and @name = '0-1/state']</value>
      <webElementGuid>9d51b615-58de-48bb-894f-28a9b008793c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
