<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hs_form_target_widget_1756331635880-313_2</name>
   <tag></tag>
   <elementGuidId>b952c06d-c051-431b-911d-e811867c9d71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;hs_form_target_widget_1756331635880-3133860052293-label-2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'hs_form_target_widget_1756331635880-3133860052293-label-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Scribe&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e433d45-4c10-4beb-8d69-dc5c97e0d9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>934e89c2-dffc-42ca-8855-d883dda7bcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>CheckboxInput</value>
      <webElementGuid>5b0a5a37-b5f7-40db-a1a4-109b8880f844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-3133860052293-input-2</value>
      <webElementGuid>45fa5d84-ad73-462d-9328-7b3fe3275b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0-1/what_evaa_features_are_you_interested_in_</value>
      <webElementGuid>ab863bbe-766f-4f76-b8ae-6ba17edc0eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-3133860052293-label-2</value>
      <webElementGuid>e318f3ac-8b5e-4376-83fa-49406a13ead8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d37eda0-fd21-4f29-b830-9daead809a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-CheckboxInput</value>
      <webElementGuid>cbe47f74-a0c1-44e7-ba0f-7cdb101b1831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Scribe</value>
      <webElementGuid>e1435a2c-6f17-4473-b94e-9782411da3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e6898d6a5bb7d924cbecee3d713917e3</value>
      <webElementGuid>b18213b0-80da-44ab-a4fe-61310c443085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'hs_form_target_widget_1756331635880-3133860052293-label-2']</value>
      <webElementGuid>012d7119-24ac-4491-8a07-47dc2714ba01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'hs_form_target_widget_1756331635880-3133860052293-label-2']</value>
      <webElementGuid>4868cfab-e454-4967-a541-20a75553e5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'hs_form_target_widget_1756331635880-3133860052293-input-2' and @name = '0-1/what_evaa_features_are_you_interested_in_']</value>
      <webElementGuid>b1b1b09b-117f-4d3c-bf26-050653650abe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
