<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hs_form_target_widget_1756331635880-313_1</name>
   <tag></tag>
   <elementGuidId>d35b5f5d-2345-4b00-98de-c19460ec9353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;hs_form_target_widget_1756331635880-3133860052293-label-1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'hs_form_target_widget_1756331635880-3133860052293-label-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Billing Assistant&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>867dc0d4-b546-4137-8b47-350cbc11292a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d081e9dc-bf63-48b2-9ba1-0b0dba359e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hsfc-id</name>
      <type>Main</type>
      <value>CheckboxInput</value>
      <webElementGuid>1bb8d298-6a18-48c7-9ed2-34d50b28906c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-3133860052293-input-1</value>
      <webElementGuid>58e377a0-9207-46ef-87ec-f6fd6a6bac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0-1/what_evaa_features_are_you_interested_in_</value>
      <webElementGuid>e362724a-3653-4382-8fc8-7c20c2c62597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>hs_form_target_widget_1756331635880-3133860052293-label-1</value>
      <webElementGuid>81b8b09e-4af5-44c9-8d8d-7dd744e591bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f49295d-cac7-4de1-94f9-9a835798a66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-CheckboxInput</value>
      <webElementGuid>c481e6f0-63a8-4532-9a4b-a61992549c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>RCM Script</value>
      <webElementGuid>10414643-7709-4a07-ab42-b1d5150f0ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-495a0e85a6d794d1eeb1ed2e5d3b06e7</value>
      <webElementGuid>6b3e8ec7-909d-4ea3-a964-ac7e22d117ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'hs_form_target_widget_1756331635880-3133860052293-label-1']</value>
      <webElementGuid>8849c034-d4f8-4e6c-b0be-b522d97c5ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'hs_form_target_widget_1756331635880-3133860052293-label-1']</value>
      <webElementGuid>55d08a27-a49d-4ff1-b94a-1971b0b94dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'hs_form_target_widget_1756331635880-3133860052293-input-1' and @name = '0-1/what_evaa_features_are_you_interested_in_']</value>
      <webElementGuid>6dc68d5b-69a5-460b-a0b1-a8b2c8b2a8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
