<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Other</name>
   <tag></tag>
   <elementGuidId>82e0825e-72d5-4bc5-9458-aa1652797512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hsfc-DropdownInput .hsfc-DropdownOptions__List__ListItem:nth-child(17)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-DropdownInput ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-DropdownOptions__List__ListItem ') and (position() = 17)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Other&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>42516cc3-d05d-4a5e-80eb-7259ad9d63fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4c3f742d-a169-44f2-8c86-2b7c31699944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>421d5cb2-9edd-4178-98bc-af428374a87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66e30104-bf47-4095-a29f-0adde91ec0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hsfc-DropdownOptions__List__ListItem</value>
      <webElementGuid>a2b8513a-dfed-48f0-ab63-af99e9f0984e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other</value>
      <webElementGuid>09e7b75d-86c5-4b46-a028-3414ac589644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1ff0bcfcce842c5c2af56321ed614fe4</value>
      <webElementGuid>2fd97038-39ba-478b-ad3e-e23a619cb278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-DropdownInput ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-DropdownOptions__List__ListItem ') and (position() = 17)]</value>
      <webElementGuid>de042aff-0f14-4943-b559-df25884c8085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-DropdownInput ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-DropdownOptions__List__ListItem ') and (position() = 17)]</value>
      <webElementGuid>a9b9ada6-e0bd-442d-bdac-024c52fe381c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Other' or . = 'Other')]</value>
      <webElementGuid>f089c888-e76b-4f6d-b7d5-ef44594c8206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
