<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Email</name>
   <tag></tag>
   <elementGuidId>9b0ec900-f784-45d6-b165-b4adf1a7f627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hsfc-EmailField span span:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-EmailField ')]//span//*[(name() = 'span') and (position() = 1)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Email&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25a4ec32-9c0d-4c51-98a8-8c7ddc322594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>fc6505ee-7f7a-43b5-88bc-1130a694e07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9bb094f3836ce538ff0f856a6aa5c8fb</value>
      <webElementGuid>6b014895-dbd1-4e5e-be41-e0ca89376eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-EmailField ')]//span//*[(name() = 'span') and (position() = 1)]</value>
      <webElementGuid>db643f7b-dfd5-4e49-90f5-6f5ad4e0d594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hsfc-EmailField ')]//span//*[(name() = 'span') and (position() = 1)]</value>
      <webElementGuid>25d85878-46ba-4cfd-9b43-f23880b1c120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Email' or . = 'Email')]</value>
      <webElementGuid>668116e5-9cd6-4c3c-9e8e-d6d1a1ae52f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
