<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>evaa img</name>
   <tag></tag>
   <elementGuidId>2cad98be-be6c-4697-84ab-17085baec45c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;EVAA.AI&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_main']/div/div/span/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;evaa ai logo&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>91f06a70-ba83-4cd5-b6e5-7f06041ca3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://evaaaidev.wpenginepowered.com/wp-content/uploads/2025/12/evaa-ai-logo.webp</value>
      <webElementGuid>84e3f429-2091-45ff-a584-39b0ef8a9321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1360aed5-7efc-479a-9955-9a27d93815fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>987cf8af-6a93-46f6-992f-b687475e2537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>EVAA.AI</value>
      <webElementGuid>47930a08-0a40-4898-a2ca-60d7c39fcfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>evaa ai logo</value>
      <webElementGuid>c5bddc54-2b6f-453e-8353-c98a1d20a0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_main&quot;)/div[@class=&quot;container av-logo-container&quot;]/div[@class=&quot;inner-container&quot;]/span[@class=&quot;logo avia-standard-logo&quot;]/a[1]/img[1]</value>
      <webElementGuid>28b7c54c-66b6-442c-bf5a-b1f844088b26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_main']/div/div/span/a/img</value>
      <webElementGuid>f2168683-62c2-459b-a2dd-463bb96aea1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='EVAA.AI']</value>
      <webElementGuid>450bf00f-abdd-41a3-a5c1-f766adde8d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ced25d8c-7d68-4ce9-a432-c7cce6855470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://evaaaidev.wpenginepowered.com/wp-content/uploads/2025/12/evaa-ai-logo.webp' and @alt = 'EVAA.AI' and @title = 'evaa ai logo']</value>
      <webElementGuid>26fc1137-4ecc-4f18-a990-9c28ccdbfd73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
