<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Sign Up</name>
   <tag></tag>
   <elementGuidId>321fbe68-39f4-404d-a05e-0810f14cf90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-10837</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-10837']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-item-10837</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>927cdae1-d83e-4805-95df-de0e18c29ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item-10837</value>
      <webElementGuid>7e2ae516-04ca-45d4-9353-9b34b658314e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avia-button avia-size-small avia-color-theme-color ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-10837 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto</value>
      <webElementGuid>e5693671-ed00-4231-945a-ec0e3b9d582a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>fdf7b554-3fa6-4347-a277-c4bf20dfa066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-10837&quot;)</value>
      <webElementGuid>48cd89b4-5866-44f2-8280-e4574bbd7497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-item-10837']</value>
      <webElementGuid>c6d54768-eef6-4036-a48f-63c124a2bffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ubermenu-nav-main-1099-avia']/li[8]</value>
      <webElementGuid>aabda1c1-9a94-4ce7-9071-272e06c4eb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::li[1]</value>
      <webElementGuid>327ac72b-2af6-41cf-a19e-d09a6f30d95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::li[2]</value>
      <webElementGuid>95787869-b684-4c83-aa8f-81a896fc4082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::li[1]</value>
      <webElementGuid>550dec94-15f8-44b9-9c95-11b9f75c7ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>0c8d2f1c-f647-4569-a069-ef0e401ea799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'menu-item-10837' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>8d3130cd-d2e7-4eb9-b115-8a2b56390256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
